-- Web Push para novidades da vitrine da Dulelis.
alter table if exists public.clientes
  add column if not exists push_marketing_consent boolean not null default false,
  add column if not exists push_marketing_consent_at timestamptz;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  expiration_time bigint,
  user_agent text,
  ativo boolean not null default true,
  consentido_em timestamptz not null default now(),
  cancelado_em timestamptz,
  ultimo_sucesso_em timestamptz,
  ultima_falha_em timestamptz,
  falhas_consecutivas integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_push_subscriptions_cliente
  on public.push_subscriptions(cliente_id);
create index if not exists idx_push_subscriptions_ativas
  on public.push_subscriptions(ativo) where ativo = true;

create table if not exists public.push_campaigns (
  id bigint generated by default as identity primary key,
  titulo text not null,
  mensagem text not null,
  url text not null default '/',
  status text not null default 'queued'
    check (status in ('queued', 'sending', 'partial', 'completed', 'failed')),
  total_destinatarios integer not null default 0,
  total_enviados integer not null default 0,
  total_falhas integer not null default 0,
  iniciado_em timestamptz,
  concluido_em timestamptz,
  created_at timestamptz not null default now()
);

alter table if exists public.push_campaigns
  add column if not exists publico text not null default 'all',
  add column if not exists origem text not null default 'manual',
  add column if not exists chave_automacao text;

create unique index if not exists idx_push_campaigns_chave_automacao
  on public.push_campaigns(chave_automacao)
  where chave_automacao is not null;

create table if not exists public.push_birthday_automation (
  id smallint primary key check (id = 1),
  ativo boolean not null default false,
  titulo text not null default 'Feliz aniversário!',
  mensagem text not null default 'A Dulelis deseja um dia muito especial para você. Abra o delivery e confira nossas novidades!',
  url text not null default '/',
  updated_at timestamptz not null default now()
);

insert into public.push_birthday_automation (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.push_campaign_deliveries (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.push_campaigns(id) on delete cascade,
  subscription_id bigint not null references public.push_subscriptions(id) on delete cascade,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'sent', 'failed', 'expired', 'skipped')),
  tentativas integer not null default 0,
  erro text,
  processado_em timestamptz,
  created_at timestamptz not null default now(),
  unique(campaign_id, subscription_id)
);

create index if not exists idx_push_deliveries_fila
  on public.push_campaign_deliveries(campaign_id, status, id);

alter table if exists public.push_campaign_deliveries
  add column if not exists tentativas integer not null default 0;

alter table public.push_subscriptions enable row level security;
alter table public.push_campaigns enable row level security;
alter table public.push_campaign_deliveries enable row level security;
alter table public.push_birthday_automation enable row level security;

revoke all on table public.push_subscriptions from anon, authenticated;
revoke all on table public.push_campaigns from anon, authenticated;
revoke all on table public.push_campaign_deliveries from anon, authenticated;
revoke all on table public.push_birthday_automation from anon, authenticated;

notify pgrst, 'reload schema';
