-- Configuracoes gerais da loja (horario de funcionamento da vitrine)
create table if not exists public.configuracoes_loja (
  id bigint generated by default as identity primary key,
  cidade_atendida text not null default 'Navegantes',
  tempo_preparo_min integer not null default 30,
  tempo_preparo_max integer not null default 45,
  tempo_entrega_min integer not null default 15,
  tempo_entrega_max integer not null default 30,
  hora_abertura time not null default '08:00:00',
  hora_fechamento time not null default '18:00:00',
  dias_semana text[] not null default array['domingo','segunda','terca','quarta','quinta','sexta','sabado'],
  categorias_produtos text[] not null default array['Bolos','Doces','Salgados','Bebidas','Produtos naturais','Personalizado'],
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint configuracoes_loja_tempos_check check (
    tempo_preparo_min between 0 and 1440
    and tempo_preparo_max between tempo_preparo_min and 1440
    and tempo_entrega_min between 0 and 1440
    and tempo_entrega_max between tempo_entrega_min and 1440
  )
);

alter table if exists public.configuracoes_loja
  add column if not exists cidade_atendida text not null default 'Navegantes';

alter table if exists public.configuracoes_loja
  add column if not exists tempo_preparo_min integer not null default 30,
  add column if not exists tempo_preparo_max integer not null default 45,
  add column if not exists tempo_entrega_min integer not null default 15,
  add column if not exists tempo_entrega_max integer not null default 30;

alter table if exists public.configuracoes_loja
  add column if not exists categorias_produtos text[] not null
  default array['Bolos','Doces','Salgados','Bebidas','Produtos naturais','Personalizado'];

-- Mantem updated_at atualizado em updates
create or replace function public.touch_updated_at_configuracoes_loja()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_updated_at_configuracoes_loja on public.configuracoes_loja;
create trigger trg_touch_updated_at_configuracoes_loja
before update on public.configuracoes_loja
for each row
execute function public.touch_updated_at_configuracoes_loja();

-- Garante ao menos um registro padrao
insert into public.configuracoes_loja (hora_abertura, hora_fechamento, dias_semana, ativo)
select
  '08:00:00'::time,
  '18:00:00'::time,
  array['domingo','segunda','terca','quarta','quinta','sexta','sabado']::text[],
  true
where not exists (select 1 from public.configuracoes_loja);
