-- Segurança para operações administrativas destrutivas.
-- Execute este arquivo no SQL Editor do Supabase antes de usar "Resetar dados da vitrine".

create table if not exists public.admin_reset_backups (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  clientes jsonb not null default '[]'::jsonb,
  pedidos jsonb not null default '[]'::jsonb,
  password_reset_tokens jsonb not null default '[]'::jsonb,
  quantidade_clientes integer not null default 0,
  quantidade_pedidos integer not null default 0,
  quantidade_tokens integer not null default 0
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor text not null,
  actor_ip text,
  actor_user_agent text,
  action text not null,
  details jsonb not null default '{}'::jsonb
);

alter table public.admin_reset_backups enable row level security;
alter table public.admin_audit_logs enable row level security;

revoke all on table public.admin_reset_backups from anon, authenticated;
revoke all on table public.admin_audit_logs from anon, authenticated;

create or replace function public.admin_reset_public_data(
  actor_ip text default null,
  actor_user_agent text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  backup_id bigint;
  clientes_backup jsonb;
  pedidos_backup jsonb;
  tokens_backup jsonb;
  clientes_count integer;
  pedidos_count integer;
  tokens_count integer;
begin
  lock table public.clientes, public.pedidos, public.clientes_password_reset_tokens in exclusive mode;

  select coalesce(jsonb_agg(to_jsonb(c)), '[]'::jsonb), count(*)::integer
    into clientes_backup, clientes_count
    from public.clientes c;
  select coalesce(jsonb_agg(to_jsonb(p)), '[]'::jsonb), count(*)::integer
    into pedidos_backup, pedidos_count
    from public.pedidos p;
  select coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb), count(*)::integer
    into tokens_backup, tokens_count
    from public.clientes_password_reset_tokens t;

  insert into public.admin_reset_backups (
    clientes,
    pedidos,
    password_reset_tokens,
    quantidade_clientes,
    quantidade_pedidos,
    quantidade_tokens
  ) values (
    clientes_backup,
    pedidos_backup,
    tokens_backup,
    clientes_count,
    pedidos_count,
    tokens_count
  ) returning id into backup_id;

  delete from public.clientes_password_reset_tokens;
  delete from public.pedidos;
  delete from public.clientes;

  insert into public.admin_audit_logs (actor, actor_ip, actor_user_agent, action, details)
  values (
    'admin',
    left(actor_ip, 200),
    left(actor_user_agent, 500),
    'reset_public_data',
    jsonb_build_object(
      'backup_id', backup_id,
      'clientes_removidos', clientes_count,
      'pedidos_removidos', pedidos_count,
      'tokens_removidos', tokens_count
    )
  );

  return jsonb_build_object(
    'backup_id', backup_id,
    'clientes_removidos', clientes_count,
    'pedidos_removidos', pedidos_count,
    'tokens_removidos', tokens_count
  );
end;
$$;

revoke all on function public.admin_reset_public_data(text, text) from public, anon, authenticated;
grant execute on function public.admin_reset_public_data(text, text) to service_role;
