-- Fundacao para delivery imediato e encomendas agendadas no mesmo app.
-- Esta migracao e idempotente e preserva os registros existentes.

begin;

-- Um pedido passa a apontar para o cadastro compartilhado do cliente.
-- Os dados copiados no proprio pedido continuam sendo o retrato historico da compra.
alter table if exists public.pedidos
  add column if not exists cliente_id bigint,
  add column if not exists tipo_pedido text not null default 'delivery',
  add column if not exists canal_origem text not null default 'app',
  add column if not exists tipo_recebimento text,
  add column if not exists agendado_para timestamptz,
  add column if not exists status_producao text,
  add column if not exists valor_sinal numeric(12,2) not null default 0,
  add column if not exists saldo_restante numeric(12,2),
  add column if not exists detalhes_encomenda jsonb not null default '{}'::jsonb,
  add column if not exists observacao text,
  add column if not exists troco_para numeric(12,2);

update public.pedidos
set tipo_pedido = 'delivery'
where tipo_pedido is null or btrim(tipo_pedido) = '';

update public.pedidos
set canal_origem = 'app'
where canal_origem is null or btrim(canal_origem) = '';

-- Converte a marcacao legada de retirada que ficava apenas na observacao.
-- Bancos mais antigos podem ainda nao ter a coluna observacao. O SQL dinamico
-- evita que o PostgreSQL tente resolver uma coluna inexistente ao ler o arquivo.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'pedidos'
      and column_name = 'observacao'
  ) then
    execute $sql$
      update public.pedidos
      set tipo_recebimento = case
        when lower(coalesce(observacao, '')) like '%tipo de entrega: retirar no balcao%'
          then 'retirada'
        else 'entrega'
      end
      where tipo_recebimento is null or btrim(tipo_recebimento) = ''
    $sql$;
  else
    update public.pedidos
    set tipo_recebimento = 'entrega'
    where tipo_recebimento is null or btrim(tipo_recebimento) = '';
  end if;
end
$$;

-- Vincula pedidos antigos pelo WhatsApp normalizado, sem apagar o snapshot historico.
with clientes_normalizados as (
  select distinct on (regexp_replace(coalesce(whatsapp, ''), '[^0-9]', '', 'g'))
    id,
    regexp_replace(coalesce(whatsapp, ''), '[^0-9]', '', 'g') as whatsapp_normalizado
  from public.clientes
  where length(regexp_replace(coalesce(whatsapp, ''), '[^0-9]', '', 'g')) >= 10
  order by regexp_replace(coalesce(whatsapp, ''), '[^0-9]', '', 'g'), id
)
update public.pedidos p
set cliente_id = c.id
from clientes_normalizados c
where p.cliente_id is null
  and regexp_replace(coalesce(p.whatsapp, ''), '[^0-9]', '', 'g') = c.whatsapp_normalizado;

create index if not exists idx_pedidos_cliente_id on public.pedidos(cliente_id);
create index if not exists idx_pedidos_tipo_agendamento
  on public.pedidos(tipo_pedido, agendado_para);
create index if not exists idx_pedidos_status_producao
  on public.pedidos(status_producao);
create index if not exists idx_clientes_whatsapp_normalizado
  on public.clientes ((regexp_replace(coalesce(whatsapp, ''), '[^0-9]', '', 'g')));

do $$
begin
  if to_regclass('public.pedidos') is not null
    and to_regclass('public.clientes') is not null
    and not exists (
      select 1
      from pg_constraint
      where conname = 'pedidos_cliente_id_fkey'
        and conrelid = 'public.pedidos'::regclass
    ) then
    alter table public.pedidos
      add constraint pedidos_cliente_id_fkey
      foreign key (cliente_id) references public.clientes(id)
      on update cascade on delete set null;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'pedidos_tipo_pedido_check'
      and conrelid = 'public.pedidos'::regclass
  ) then
    alter table public.pedidos
      add constraint pedidos_tipo_pedido_check
      check (tipo_pedido in ('delivery', 'encomenda'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'pedidos_tipo_recebimento_check'
      and conrelid = 'public.pedidos'::regclass
  ) then
    alter table public.pedidos
      add constraint pedidos_tipo_recebimento_check
      check (tipo_recebimento is null or tipo_recebimento in ('entrega', 'retirada'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'pedidos_valores_encomenda_check'
      and conrelid = 'public.pedidos'::regclass
  ) then
    alter table public.pedidos
      add constraint pedidos_valores_encomenda_check
      check (
        valor_sinal >= 0
        and (saldo_restante is null or saldo_restante >= 0)
      );
  end if;
end
$$;

-- Configuracao independente do horario do delivery.
create table if not exists public.configuracoes_encomendas (
  id bigint generated by default as identity primary key,
  ativo boolean not null default true,
  timezone text not null default 'America/Sao_Paulo',
  antecedencia_minima_horas integer not null default 48,
  horizonte_maximo_dias integer not null default 120,
  hora_inicio time not null default '08:00:00',
  hora_fim time not null default '18:00:00',
  intervalo_slot_minutos integer not null default 60,
  capacidade_padrao_por_slot integer not null default 4,
  dias_semana text[] not null default array['segunda','terca','quarta','quinta','sexta','sabado'],
  permite_entrega boolean not null default true,
  permite_retirada boolean not null default true,
  percentual_sinal numeric(5,2) not null default 50,
  permite_pagamento_integral boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint configuracoes_encomendas_prazos_check check (
    antecedencia_minima_horas >= 0
    and horizonte_maximo_dias >= 1
    and intervalo_slot_minutos between 15 and 1440
    and capacidade_padrao_por_slot >= 1
    and percentual_sinal between 0 and 100
  )
);

alter table public.configuracoes_encomendas
  add column if not exists percentual_sinal numeric(5,2) not null default 50,
  add column if not exists permite_pagamento_integral boolean not null default true;

insert into public.configuracoes_encomendas (
  ativo,
  timezone,
  antecedencia_minima_horas,
  horizonte_maximo_dias,
  hora_inicio,
  hora_fim,
  intervalo_slot_minutos,
  capacidade_padrao_por_slot,
  dias_semana,
  permite_entrega,
  permite_retirada
)
select
  true,
  'America/Sao_Paulo',
  48,
  120,
  '08:00:00'::time,
  '18:00:00'::time,
  60,
  4,
  array['segunda','terca','quarta','quinta','sexta','sabado']::text[],
  true,
  true
where not exists (select 1 from public.configuracoes_encomendas);

create or replace function public.touch_updated_at_configuracoes_encomendas()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_updated_at_configuracoes_encomendas
  on public.configuracoes_encomendas;
create trigger trg_touch_updated_at_configuracoes_encomendas
before update on public.configuracoes_encomendas
for each row execute function public.touch_updated_at_configuracoes_encomendas();

-- Excecoes de agenda: feriados, manutencao ou periodos sem producao.
create table if not exists public.bloqueios_encomendas (
  id bigint generated by default as identity primary key,
  inicio timestamptz not null,
  fim timestamptz not null,
  motivo text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  constraint bloqueios_encomendas_periodo_check check (fim > inicio)
);

create index if not exists idx_bloqueios_encomendas_periodo
  on public.bloqueios_encomendas(inicio, fim)
  where ativo = true;

-- Capacidade especifica de uma faixa; quando ausente, vale a configuracao padrao.
create table if not exists public.capacidade_encomendas (
  id bigint generated by default as identity primary key,
  data date not null,
  hora_inicio time not null,
  hora_fim time not null,
  capacidade_total integer not null,
  ativo boolean not null default true,
  observacao text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint capacidade_encomendas_valores_check check (
    hora_fim > hora_inicio and capacidade_total >= 0
  ),
  constraint capacidade_encomendas_faixa_unique unique (data, hora_inicio, hora_fim)
);

create index if not exists idx_capacidade_encomendas_data
  on public.capacidade_encomendas(data)
  where ativo = true;

-- A validacao final da agenda acontece no banco para impedir duas reservas
-- simultaneas de ultrapassarem a capacidade do mesmo horario.
create or replace function public.validar_agendamento_encomenda()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  config public.configuracoes_encomendas%rowtype;
  horario_local timestamp;
  data_local date;
  hora_local time;
  dia_semana text;
  capacidade_slot integer;
  pedidos_no_slot integer;
begin
  if new.tipo_pedido <> 'encomenda' then
    return new;
  end if;

  -- Alteracoes comuns de producao/pagamento nao precisam revalidar a agenda.
  -- Ao cancelar, sempre permitimos a liberacao da vaga; ao reativar uma
  -- encomenda cancelada, a capacidade volta a ser conferida abaixo.
  if tg_op = 'UPDATE'
    and new.tipo_pedido is not distinct from old.tipo_pedido
    and new.agendado_para is not distinct from old.agendado_para
  then
    if lower(coalesce(new.status_pedido, '')) in ('cancelado', 'cancelada', 'recusado')
      or lower(coalesce(new.status_producao, '')) = 'cancelada'
      or (
        lower(coalesce(old.status_pedido, '')) not in ('cancelado', 'cancelada', 'recusado')
        and lower(coalesce(old.status_producao, '')) <> 'cancelada'
      )
    then
      return new;
    end if;
  end if;

  select * into config
  from public.configuracoes_encomendas
  order by id
  limit 1;

  if not found or config.ativo = false then
    raise exception 'As encomendas estao fechadas no momento.' using errcode = 'P0001';
  end if;
  if new.agendado_para is null then
    raise exception 'Informe a data e o horario da encomenda.' using errcode = '23514';
  end if;
  if new.agendado_para < now() + make_interval(hours => config.antecedencia_minima_horas) then
    raise exception 'A encomenda nao respeita a antecedencia minima.' using errcode = 'P0001';
  end if;
  if new.agendado_para > now() + make_interval(days => config.horizonte_maximo_dias) then
    raise exception 'A data da encomenda esta alem do periodo disponivel.' using errcode = 'P0001';
  end if;

  horario_local := new.agendado_para at time zone config.timezone;
  data_local := horario_local::date;
  hora_local := horario_local::time;
  dia_semana := (array['domingo','segunda','terca','quarta','quinta','sexta','sabado'])[
    extract(dow from horario_local)::integer + 1
  ];

  if not (dia_semana = any(config.dias_semana)) then
    raise exception 'Nao recebemos encomendas para esse dia da semana.' using errcode = 'P0001';
  end if;
  if hora_local < config.hora_inicio or hora_local >= config.hora_fim then
    raise exception 'Horario fora da agenda de encomendas.' using errcode = 'P0001';
  end if;
  if mod(
    (extract(epoch from (hora_local - config.hora_inicio)) / 60)::integer,
    config.intervalo_slot_minutos
  ) <> 0 then
    raise exception 'Escolha um horario valido da agenda de encomendas.' using errcode = 'P0001';
  end if;
  if exists (
    select 1
    from public.bloqueios_encomendas b
    where b.ativo = true
      and new.agendado_para >= b.inicio
      and new.agendado_para < b.fim
  ) then
    raise exception 'Esse horario esta bloqueado para encomendas.' using errcode = 'P0001';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(to_char(new.agendado_para at time zone 'UTC', 'YYYY-MM-DD HH24:MI'), 0)
  );

  select c.capacidade_total
  into capacidade_slot
  from public.capacidade_encomendas c
  where c.ativo = true
    and c.data = data_local
    and hora_local >= c.hora_inicio
    and hora_local < c.hora_fim
  order by c.hora_inicio desc
  limit 1;

  capacidade_slot := coalesce(capacidade_slot, config.capacidade_padrao_por_slot);
  select count(*)::integer
  into pedidos_no_slot
  from public.pedidos p
  where p.tipo_pedido = 'encomenda'
    and p.agendado_para = new.agendado_para
    and p.id is distinct from new.id
    and lower(coalesce(p.status_pedido, '')) not in ('cancelado', 'cancelada', 'recusado');

  if capacidade_slot <= pedidos_no_slot then
    raise exception 'Esse horario acabou de atingir a capacidade maxima.' using errcode = 'P0001';
  end if;

  new.status_producao := coalesce(nullif(btrim(new.status_producao), ''), 'aguardando_confirmacao');
  return new;
end;
$$;

drop trigger if exists trg_validar_agendamento_encomenda on public.pedidos;
create trigger trg_validar_agendamento_encomenda
before insert or update of tipo_pedido, agendado_para, status_pedido, status_producao on public.pedidos
for each row execute function public.validar_agendamento_encomenda();

-- O estoque atual segue sendo o catalogo; estes campos definem onde o produto aparece.
alter table if exists public.estoque
  add column if not exists disponivel_delivery boolean not null default true,
  add column if not exists disponivel_encomenda boolean not null default false,
  add column if not exists prazo_minimo_encomenda_horas integer not null default 48,
  add column if not exists limite_por_encomenda integer,
  add column if not exists opcoes_encomenda jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'estoque_regras_encomenda_check'
      and conrelid = 'public.estoque'::regclass
  ) then
    alter table public.estoque
      add constraint estoque_regras_encomenda_check
      check (
        prazo_minimo_encomenda_horas >= 0
        and (limite_por_encomenda is null or limite_por_encomenda >= 1)
      );
  end if;
end
$$;

create index if not exists idx_estoque_disponivel_encomenda
  on public.estoque(disponivel_encomenda)
  where disponivel_encomenda = true;

-- Historico estruturado para auditoria e futuras notificacoes.
create table if not exists public.pedido_eventos (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  tipo text not null,
  descricao text,
  dados jsonb not null default '{}'::jsonb,
  criado_por text not null default 'sistema',
  created_at timestamptz not null default now()
);

create index if not exists idx_pedido_eventos_pedido_data
  on public.pedido_eventos(pedido_id, created_at desc);

create unique index if not exists idx_pedido_eventos_pagamento_encomenda_unico
  on public.pedido_eventos ((dados->>'pagamento_id'))
  where tipo = 'pagamento_encomenda_aprovado'
    and nullif(dados->>'pagamento_id', '') is not null;

-- Aplica sinal/saldo em uma unica transacao. O bloqueio da linha impede que
-- dois webhooks simultaneos sobrescrevam o saldo calculado pelo outro.
create or replace function public.registrar_pagamento_encomenda(
  p_pedido_id bigint,
  p_pagamento_id text,
  p_referencia text,
  p_tipo_pagamento text,
  p_valor_pago numeric,
  p_status text default 'approved',
  p_forma_pagamento text default 'Mercado Pago'
)
returns table (
  aplicado boolean,
  valor_sinal numeric,
  saldo_restante numeric,
  pagamento_completo boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  pedido public.pedidos%rowtype;
  valor_aplicado numeric;
  novo_sinal numeric;
  novo_saldo numeric;
begin
  if nullif(btrim(coalesce(p_pagamento_id, '')), '') is null then
    raise exception 'Identificador do pagamento ausente.' using errcode = '22023';
  end if;
  if lower(coalesce(p_tipo_pagamento, '')) not in ('sinal', 'saldo', 'integral') then
    raise exception 'Tipo de pagamento da encomenda invalido.' using errcode = '22023';
  end if;

  select * into pedido
  from public.pedidos
  where id = p_pedido_id
  for update;

  if not found or pedido.tipo_pedido <> 'encomenda' then
    raise exception 'Encomenda nao encontrada.' using errcode = 'P0002';
  end if;

  if exists (
    select 1 from public.pedido_eventos e
    where e.tipo = 'pagamento_encomenda_aprovado'
      and e.dados->>'pagamento_id' = p_pagamento_id
  ) then
    return query select
      false,
      coalesce(pedido.valor_sinal, 0),
      coalesce(pedido.saldo_restante, greatest(coalesce(pedido.total, 0) - coalesce(pedido.valor_sinal, 0), 0)),
      coalesce(pedido.saldo_restante, 0) <= 0.009;
    return;
  end if;

  valor_aplicado := least(
    greatest(coalesce(pedido.saldo_restante, pedido.total - coalesce(pedido.valor_sinal, 0), 0), 0),
    greatest(coalesce(p_valor_pago, 0), 0)
  );
  if valor_aplicado <= 0 then
    raise exception 'Valor do pagamento invalido ou encomenda ja quitada.' using errcode = '22023';
  end if;

  novo_sinal := case
    when lower(p_tipo_pagamento) = 'sinal'
      then least(coalesce(pedido.total, 0), coalesce(pedido.valor_sinal, 0) + valor_aplicado)
    else coalesce(pedido.valor_sinal, 0)
  end;
  novo_saldo := greatest(
    coalesce(pedido.saldo_restante, pedido.total - coalesce(pedido.valor_sinal, 0), 0) - valor_aplicado,
    0
  );

  update public.pedidos
  set
    status_pagamento = case when novo_saldo <= 0.009 then 'approved' else 'partial' end,
    pagamento_id = p_pagamento_id,
    pagamento_referencia = nullif(btrim(coalesce(p_referencia, '')), ''),
    pagamento_atualizado_em = now(),
    forma_pagamento = coalesce(nullif(btrim(coalesce(p_forma_pagamento, '')), ''), forma_pagamento),
    valor_sinal = novo_sinal,
    saldo_restante = case when novo_saldo <= 0.009 then 0 else novo_saldo end
  where id = pedido.id;

  insert into public.pedido_eventos (pedido_id, tipo, descricao, dados, criado_por)
  values (
    pedido.id,
    'pagamento_encomenda_aprovado',
    case when novo_saldo <= 0.009
      then 'Pagamento integral da encomenda aprovado.'
      else 'Sinal da encomenda aprovado.'
    end,
    jsonb_build_object(
      'pagamento_id', p_pagamento_id,
      'referencia', p_referencia,
      'tipo_pagamento', lower(p_tipo_pagamento),
      'valor_pago', valor_aplicado,
      'saldo_restante', case when novo_saldo <= 0.009 then 0 else novo_saldo end,
      'status_origem', p_status
    ),
    'mercado_pago'
  );

  return query select
    true,
    novo_sinal,
    case when novo_saldo <= 0.009 then 0 else novo_saldo end,
    novo_saldo <= 0.009;
end;
$$;

revoke all on function public.registrar_pagamento_encomenda(bigint, text, text, text, numeric, text, text) from public, anon, authenticated;
grant execute on function public.registrar_pagamento_encomenda(bigint, text, text, text, numeric, text, text) to service_role;

-- Reservas temporarias impedem que carrinhos abandonados prendam estoque para sempre.
create table if not exists public.reservas_estoque (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  produto_id bigint not null references public.estoque(id) on delete cascade,
  quantidade integer not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reservas_estoque_quantidade_check check (quantidade > 0),
  constraint reservas_estoque_cliente_produto_unique unique (cliente_id, produto_id)
);

create index if not exists idx_reservas_estoque_expiracao
  on public.reservas_estoque(expires_at);

create or replace function public.liberar_reservas_estoque_expiradas()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  total_liberado integer := 0;
begin
  with expiradas as (
    delete from public.reservas_estoque
    where expires_at <= now()
    returning produto_id, quantidade
  ), somas as (
    select produto_id, sum(quantidade)::integer as quantidade
    from expiradas
    group by produto_id
  ), atualizadas as (
    update public.estoque e
    set quantidade = coalesce(e.quantidade, 0) + s.quantidade
    from somas s
    where e.id = s.produto_id
    returning s.quantidade
  )
  select coalesce(sum(quantidade), 0)::integer
  into total_liberado
  from atualizadas;

  return total_liberado;
end;
$$;

create or replace function public.ajustar_reserva_estoque(
  p_cliente_id bigint,
  p_produto_id bigint,
  p_delta integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  estoque_atual integer;
  reserva_atual integer;
  quantidade_movimento integer;
  novo_estoque integer;
begin
  if p_cliente_id is null or p_cliente_id <= 0
    or p_produto_id is null or p_produto_id <= 0
    or p_delta = 0 or abs(p_delta) > 50 then
    raise exception 'Parametros de reserva invalidos.' using errcode = '22023';
  end if;

  perform public.liberar_reservas_estoque_expiradas();

  select quantidade
  into estoque_atual
  from public.estoque
  where id = p_produto_id
  for update;

  if not found then
    return jsonb_build_object('updated', false, 'reason', 'not_found');
  end if;

  if p_delta < 0 then
    quantidade_movimento := abs(p_delta);
    if coalesce(estoque_atual, 0) < quantidade_movimento then
      return jsonb_build_object('updated', false, 'reason', 'insufficient');
    end if;

    novo_estoque := estoque_atual - quantidade_movimento;
    update public.estoque
    set quantidade = novo_estoque
    where id = p_produto_id;

    insert into public.reservas_estoque (
      cliente_id,
      produto_id,
      quantidade,
      expires_at,
      updated_at
    ) values (
      p_cliente_id,
      p_produto_id,
      quantidade_movimento,
      now() + interval '30 minutes',
      now()
    )
    on conflict (cliente_id, produto_id)
    do update set
      quantidade = public.reservas_estoque.quantidade + excluded.quantidade,
      expires_at = excluded.expires_at,
      updated_at = now();

    return jsonb_build_object(
      'updated', true,
      'quantidade', novo_estoque,
      'reserved', quantidade_movimento
    );
  end if;

  select quantidade
  into reserva_atual
  from public.reservas_estoque
  where cliente_id = p_cliente_id and produto_id = p_produto_id
  for update;

  if not found then
    return jsonb_build_object(
      'updated', true,
      'quantidade', estoque_atual,
      'released', 0,
      'reason', 'no_reservation'
    );
  end if;

  quantidade_movimento := least(p_delta, reserva_atual);
  novo_estoque := estoque_atual + quantidade_movimento;
  update public.estoque
  set quantidade = novo_estoque
  where id = p_produto_id;

  if quantidade_movimento >= reserva_atual then
    delete from public.reservas_estoque
    where cliente_id = p_cliente_id and produto_id = p_produto_id;
  else
    update public.reservas_estoque
    set
      quantidade = quantidade - quantidade_movimento,
      expires_at = now() + interval '30 minutes',
      updated_at = now()
    where cliente_id = p_cliente_id and produto_id = p_produto_id;
  end if;

  return jsonb_build_object(
    'updated', true,
    'quantidade', novo_estoque,
    'released', quantidade_movimento
  );
end;
$$;

create or replace function public.consumir_reservas_estoque(
  p_cliente_id bigint,
  p_itens jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  produto bigint;
  quantidade_pedida integer;
  quantidade_reservada integer;
begin
  if p_cliente_id is null or p_cliente_id <= 0
    or p_itens is null or jsonb_typeof(p_itens) <> 'array'
    or jsonb_array_length(p_itens) = 0 then
    raise exception 'Reserva do pedido invalida.' using errcode = '22023';
  end if;

  for item in select value from jsonb_array_elements(p_itens)
  loop
    produto := (item->>'id')::bigint;
    quantidade_pedida := (item->>'qtd')::integer;
    if produto <= 0 or quantidade_pedida <= 0 then
      raise exception 'Item de reserva invalido.' using errcode = '22023';
    end if;

    select quantidade
    into quantidade_reservada
    from public.reservas_estoque
    where cliente_id = p_cliente_id
      and produto_id = produto
      and expires_at > now()
    for update;

    if not found or quantidade_reservada < quantidade_pedida then
      raise exception 'Reserva de estoque insuficiente para o produto %.', produto
        using errcode = 'P0001';
    end if;

    if quantidade_reservada = quantidade_pedida then
      delete from public.reservas_estoque
      where cliente_id = p_cliente_id and produto_id = produto;
    else
      update public.reservas_estoque
      set
        quantidade = quantidade - quantidade_pedida,
        updated_at = now()
      where cliente_id = p_cliente_id and produto_id = produto;
    end if;
  end loop;

  return true;
end;
$$;

revoke all on function public.liberar_reservas_estoque_expiradas() from public, anon, authenticated;
revoke all on function public.ajustar_reserva_estoque(bigint, bigint, integer) from public, anon, authenticated;
revoke all on function public.consumir_reservas_estoque(bigint, jsonb) from public, anon, authenticated;
grant execute on function public.liberar_reservas_estoque_expiradas() to service_role;
grant execute on function public.ajustar_reserva_estoque(bigint, bigint, integer) to service_role;
grant execute on function public.consumir_reservas_estoque(bigint, jsonb) to service_role;

-- Todas as tabelas sensiveis continuam acessiveis apenas pelas APIs com service role.
alter table public.configuracoes_encomendas enable row level security;
alter table public.bloqueios_encomendas enable row level security;
alter table public.capacidade_encomendas enable row level security;
alter table public.pedido_eventos enable row level security;
alter table public.reservas_estoque enable row level security;

commit;
